name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.18.0'


      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential lcov gcovr

      - name: Clean build and deps
        run: |
          rm -rf build/
          rm -rf */build/
          rm -rf */_deps/
          rm -rf _deps/

      - name: Configure project (with coverage)
        run: cmake -S . -B build -DENABLE_COVERAGE=ON

      - name: Build unit tests
        run: cmake --build build --target tests

      - name: Run unit tests
        run: cmake --build build --target run_tests

      - name: Run code coverage (gcovr_console)
        run: |
          cmake --build build --target gcovr_console
